# Projet 1

In [35]:
import re

import pandas as pd
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt

In [2]:
book =  open("LOTR_ReturnOfTheKing.txt").read()

book_chapters = re.split(r"_Chapter \w+_",book)[1:]



In [38]:
Characters = [["aragorn","strider","the heir of isildur","king of Gondor"], ["arwen", "queen of gondor","evenstar"],
              ["bill ferny"], ["bilbo"],["boromir"], ["beregond"],["bergil"],["butterbur","barliman"],
              ["celeborn", "lord of lothlorien"],["deagol"],["denethor","steward of gondor"],["elanor"],["elendil"],
              ["elladan"], ["elrond"],["eomer"],["erestor"],["eowyn","lady of rohan"],["elrohir"],["finduilas"],
              ['fredegar bolger', "fatty","fredegar"], ["frodo","mr. underhill"],["gollum", "smeagol"],["gwaihir"],["faramir"],
              ["galadriel"],["gandalf","mithrandir", "white rider","grey Fool"],["gimli"],["glorfindel"],
              ["gothmog", "the lieutenant of morgul"],["grima","wormtongue"],["imrahil","prince imrahil"],["isildur"],
              ["king of the deads", "king of the mountains"],["legolas"],["lord of nazgul","ringwraiths","black rider", "the witch king", "king of angmar"],
              ["lotho"],["merry","meriadoc","brandybuck"],["pippin","peregrin","tooks"],["robin", "smallburrow"],
              ["rose cotton", "rosie"],["sam","samwise","gamgee"],["saruman"],["sauron","lord of mordor","lord of the dark tower"],
              ["shadowfax"],["shagrat"],["shelob"],["snaga"],["the lieutenant of the dark tower", "the lieutenant of the tower","the mouth of sauron"],
              ["tom cotton","farmer cotton" ],["theoden","king of the mark","lord of the mark"],["treebeard","fangorn"],
              ["widfara"]]

FirstName = []
for i in Characters :
    FirstName.append(i[0])



In [39]:
print("number of characters: "+ str(len(Characters)))

number of characters: 53


In [5]:
## CLEANING 

cleaned_parag =[]
for ChapterNb, Chapter in enumerate(book_chapters):
    paragraphsEnsemble = Chapter.split('\n\n')
    for parag in paragraphsEnsemble :
        parag_new = re.sub(r"[!?',;.:']", ' ', parag)
        cleaned_parag.append(parag_new.lower())
        


Data transformation

In [44]:
CoocMatrix ={}
OccurenceList={} # number of times a characters is present 
for parag in cleaned_parag: # Per paragraph, check if words are a Character

    List = []
    for w in parag.split():
        for perso in Characters:
            if w in perso and w not in List:
                List.append(perso[0])

    n = len(List)
    for i in range(n):
        for j in range(i,n):
            CoocMatrix[(List[i],List[j])] = CoocMatrix.get((List[i],List[j]) ,0)+1
            CoocMatrix[(List[j],List[i])] = CoocMatrix.get((List[j],List[i]) ,0)+1
            if(i==j):
                OccurenceList[List[i]] = OccurenceList.get((List[i]) ,0)+1

print(CoocMatrix)

{('pippin', 'pippin'): 282, ('pippin', 'gandalf'): 108, ('gandalf', 'pippin'): 108, ('pippin', 'shadowfax'): 24, ('shadowfax', 'pippin'): 24, ('pippin', 'frodo'): 37, ('frodo', 'pippin'): 37, ('gandalf', 'gandalf'): 266, ('gandalf', 'shadowfax'): 33, ('shadowfax', 'gandalf'): 33, ('gandalf', 'frodo'): 28, ('frodo', 'gandalf'): 28, ('shadowfax', 'shadowfax'): 34, ('shadowfax', 'frodo'): 6, ('frodo', 'shadowfax'): 6, ('frodo', 'frodo'): 106, ('pippin', 'denethor'): 32, ('denethor', 'pippin'): 32, ('pippin', 'boromir'): 18, ('boromir', 'pippin'): 18, ('shadowfax', 'denethor'): 8, ('denethor', 'shadowfax'): 8, ('shadowfax', 'boromir'): 4, ('boromir', 'shadowfax'): 4, ('gandalf', 'denethor'): 40, ('denethor', 'gandalf'): 40, ('gandalf', 'boromir'): 24, ('boromir', 'gandalf'): 24, ('denethor', 'denethor'): 54, ('denethor', 'boromir'): 10, ('boromir', 'denethor'): 10, ('boromir', 'boromir'): 22, ('gandalf', 'imrahil'): 25, ('imrahil', 'gandalf'): 25, ('imrahil', 'imrahil'): 48, ('imrahil', 'p

In [46]:
# DataFrame Coocurence
df = pd.DataFrame(columns = FirstName, index = FirstName)
df[:] = int(0)

for (key1,key2) in CoocMatrix:
    df[key1][key2] = CoocMatrix[(key1,key2)]
print(df)

                                 aragorn arwen bill ferny bilbo boromir  \
aragorn                              140     9          0     5       6   
arwen                                  9    26          0     2       0   
bill ferny                             0     0          0     0       0   
bilbo                                  5     2          0    32       0   
boromir                                6     0          0     0      22   
beregond                               5     0          0     1       5   
bergil                                 2     0          0     0       0   
butterbur                             22     0          0     1       0   
celeborn                               4     6          0     1       0   
deagol                                 0     0          0     0       0   
denethor                              11     0          0     1      10   
elanor                                 0     0          0     2       0   
elendil                  

In [47]:
# M : Weight regulirizator
#M = df.to_numpy().max()
MostFrequentCharac = max(OccurenceList, key=OccurenceList.get)
print(MostFrequentCharac)
M = OccurenceList[MostFrequentCharac]
M

gandalf


95

In [49]:
G = nx.Graph()
#nx.add_path(G,Characters)

A=np.matrix(df)
print(A)
#G=nx.from_numpy_matrix(A)


#plt.show()

[[10 5 1 ... 0 0 1]
 [5 102 4 ... 0 0 6]
 [1 4 32 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 6 0 ... 0 0 34]]
